<a href="https://colab.research.google.com/github/GameLooped/Primero/blob/trabajos/PANDAS_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1:
Programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla una serie con los datos por las ventas indexadas por los años, antes y despues de aplicarles un descuento de 5%

In [ ]:
import pandas as pd
inicio = int(input('Introduce el año inicial: '))
final = int(input('Introduce el año final: '))
ventas = {}
for i in range(inicio, final+1):
    if i % 2 == 0:
        ventas[i] = float(input('Introduce las ventas del año ' + str(i) +': '))

In [22]:
import pandas as pd
inicio = int(input('Introduce el año inicial: '))
final = int(input('Introduce el año final: '))
ventas = {}
for i in range(inicio, final+1):
    if i % 2 == 0:
        ventas[i] = float(input('Introduce las ventas del año ' + str(i) +': '))
serie_ventas = pd.Series(ventas)
serie_ventas_con_descuento = serie_ventas * 0.95
print("\nDatos de ventas originales:")
display(serie_ventas)
print("\nDatos de ventas con 5% de descuento:")
display(serie_ventas_con_descuento)

Introduce el año inicial: 2005
Introduce el año final: 2024
Introduce las ventas del año 2006: 15
Introduce las ventas del año 2008: 256
Introduce las ventas del año 2010: 45
Introduce las ventas del año 2012: 14
Introduce las ventas del año 2014: 28
Introduce las ventas del año 2016: 15
Introduce las ventas del año 2018: 45
Introduce las ventas del año 2020: 15
Introduce las ventas del año 2022: 24
Introduce las ventas del año 2024: 58

Datos de ventas originales:

2006     15.0
2008    256.0
2010     45.0
2012     14.0
2014     28.0
2016     15.0
2018     45.0
2020     15.0
2022     24.0
2024     58.0
dtype: float64

Datos de ventas con 5% de descuento:

2006     14.25
2008    243.20
2010     42.75
2012     13.30
2014     26.60
2016     14.25
2018     42.75
2020     14.25
2022     22.80
2024     55.10
dtype: float64

Ejercicio 2: Calculo de estadisticas basicas: media, mediana, desviación estandar- numpy para el dataframe

In [26]:
import pandas as pd
import numpy as np
#crear un dataframe
data = {'Nombre': ['Jose', 'Juan', 'Maria', 'Pedro'], 'Edad': [32, 28, 19, 21], 'Ciudad': ['Huancayo', 'Lima', 'Piura', 'Trujillo']}
df = pd.DataFrame(data)

#Calcular la media utilizando numpy
media_edad = np.mean(df['Edad'])
print(media_edad)

#Calcular la mediana utilizando numpy
mediana_edad = np.median(df['Edad'])
print(mediana_edad)

#Calcular la desviación estandar utilizando numpy
desviacion_estandar_edad = np.std(df['Edad'])
print(desviacion_estandar_edad)

#Calcular la máxima edad utilizando numpy
max_edad = np.max(df['Edad'])
print(max_edad)

#Calcular la mínima edad utilizando numpy
min_edad = np.min(df['Edad'])
print(min_edad)

25.0
24.5
5.244044240850758
32
19